version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    image: nginx
    ports:
        - 8098:80
    links:
        - fpm
    volumes:
        - ./:/var/www/laradock
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
        - ./:/var/www/laradock
    links:
        - mysql
  mysql:
    image: mysql:5.7
    ports:
        - 33061:3306
    environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=laradock
        - MYSQL_USER=root
        - MYSQL_PASSWORD=123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    links:
        - mysql
    environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - 8080:80
    volumes:
        - /sessions
    depends_on:
        - mysql


